name: PR Check Accepted
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
      - if: "contains( github.event.pull_request.labels.*.name, 'PR: Invalid')"
        run: |
          echo "::error title=Please remove invalid label"
          exit 1

      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"

      - name: copy-labels
        if: steps.check-linked-issues.outputs.linked_issues_count > 0
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: failure() && steps.check-linked-issues.outputs.linked_issues_count == 0
        with:
          labels: "PR: Invalid"

      - if: github.event.action == 'opened'
        run: |
          echo "::error title=Accept label needed"
          exit 1

  # JOB to build and test each of modified diffs
  check_accepted:
    needs: pr_checks
    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: winterjung/split@v2
        id: split
        with:
          msg: ${{ matrix.label }}
          separator: ": "
          
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        if: steps.split.outputs._0 == 'Client'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "Accepted: ${{ steps.split.outputs._0 }}, Review: ${{ steps.split.outputs._0 }}"
          # invalid-labels: 'help wanted, invalid'
          pull-request-number: "${{ github.event.pull_request.number }}"
