name: PR Check Meta
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    outputs:
      diffs: ${{ steps.diffs.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: diffs
      with:
        base: ${{ github.ref }}
        filters: |
          LAWD:
            - 'apps/main/src/modules/lawd/**'
          frontend:
            - 'frontend/**'      

 # JOB to build and test each of modified packages
  build:
    needs: pr_checks
    strategy:
      matrix:
        instance: ${{ fromJSON(needs.pr_checks.outputs.diffs) }}
    runs-on: ubuntu-latest
    steps:
      - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            valid-labels: 'Accepted: ${{ matrix.instance }}'
            # invalid-labels: 'help wanted, invalid'
            pull-request-number: '${{ github.event.pull_request.number }}'