name: PR Check Meta
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: '.github'
          sparse-checkout-cone-mode: false