name: PR Check Accepted
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    # outputs:
    #   labels: ${{ github.event.pull_request.labels.*.name }}
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@v1
        id: check-linked-issues
        with:
          exclude-branches: "release/**, dependabot/**"

      - name: copy-labels
        if: steps.check-linked-issues.outputs.linked_issues_count > 0
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.check-linked-issues.outputs.linked_issues_count == 0
        with:
          labels: PR:invalid

    # - id: diffs
    #   uses: dorny/paths-filter@v2
    #   # if: contains('["synchronize","labeled","unlabeled"]', github.event.action)
    #   with:
    #     base: ${{ github.ref }}
    #     filters: |
    #       LAWD:
    #         - 'apps/main/src/modules/lawd/**'
    #       TESTxxx:
    #         - 'frontend/**'

  # JOB to build and test each of modified diffs
  # check_accepted:
  #   needs: pr_checks
  #   strategy:
  #     matrix:
  #       instance: ${{ fromJSON(needs.pr_checks.outputs.labels) }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: jesusvasquez333/verify-pr-label-action@v1.4.0
  #       with:
  #         github-token: "${{ secrets.GITHUB_TOKEN }}"
  #         valid-labels: "Accepted: ${{ matrix.instance }}, Review: ${{ matrix.instance }}"
  #         # invalid-labels: 'help wanted, invalid'
  #         pull-request-number: "${{ github.event.pull_request.number }}"
