name: Publish packages

on:
  push:
    branches:
      - master
    paths: ['packages/**']

permissions:
  contents: write

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:

    - run: echo '${{ toJSON(github.event) }}'

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          core-ui: packages/core-ui/**
          config-eslint: packages/config-eslint/**

    - name: bump ${{ matrix.package }}
      run: npx zx scripts/npm/publish-packages.mjs -p ${{ toJSON(steps.filter.outputs.changes) }}

    - run: git status
    - run: git log
    - run: git push
